[features]
seeds = false
[programs.devnet]
programs = "9TRRoJBjrAK3BeDSL2ZVor9fw97jzcQkvw2DV3gRXCHN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/muzammil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
